### ISSUE TITLE
URGENT: Past year of activity inactive on the registry

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-website#17]
Hi, 

past year of activity is not live on the registry. need to fix this asap. 

CC @nathanbaleeta @nathanfletcher

I heard fletcher is on a contract break but wondering if we can make an exception and fix this? @lacabra this is a bit urgent due to the DPG charter that's happening in parallel. Do you think you can help? 

Screenshot attached of how the final column looks now. THANKS A LOT! 

<img width="1440" alt="Screenshot 2022-06-03 at 2 46 16 PM" src="https://user-images.githubusercontent.com/86725474/171856620-e77a2325-c7ab-4fd8-b087-c25b26d44b6c.png">

**Comment by lacabra** [comment]
This issue has been successfully resolved, check https://digitalpublicgoods.net/registry/ for the working live version.
