### ISSUE TITLE
Registry SDG visualisation

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-website#21]
The registry's SDG visualisation is showcasing numbers from when we had nominees on the registry. We need to 

1. Change the numbers to represent the DPG split by SDG
OR
2. Remove both the visualisations of DPG type and SDG altogether. 

What would be the development timeline for this? 

Here is a screen capture that explains the problem.
[https://drive.google.com/file/d/1E_3YPt68kOPy92ZS89Sh_iV-fyW2vTuu/view?usp=share_link](url)

**Comment by ricardomiron** [comment]
I see @nathanfletcher already sent a patch so this context might not be that relevant anymore but, I think the issue is not that the SDG visualization shows nominees' numbers. If you fetch the API you get the same number of DPGs, but has to do with the filters not working #22

**Comment by nathanfletcher** [comment]
Yes @ricardomiron PR [#169](https://github.com/DPGAlliance/publicgoods-scripts/pull/169) which patches it above as you stated solves it.
