### ISSUE TITLE
Filters on the DPGA registry not working

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-website#22]
The filters once unchecked and checked do not lead to the registry showing up those DPGs unless the user hits refresh. Even after hitting refresh more likely than not, the registry loads again with ALL filters. 

Please find [screengrab]([https://drive.google.com/file/d/1E_3YPt68kOPy92ZS89Sh_iV-fyW2vTuu/view?usp=share_link](url))

**Comment by nathanfletcher** [comment]
Closed by PR [#169](https://github.com/DPGAlliance/publicgoods-scripts/pull/169) publicgoods-scripts
