### ISSUE TITLE
Add "Select All" and "Select none" in filters on registry 

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-website#23]
Currently, if the user wants to sift through the DPGs, they either have to individually select or de-select all options. That causes a lot of delay. We need to add these two options to the filters on the registry.

**Comment by prajectory** [comment]
https://digitalpublicgoods.net/registry/ Hi, the select all should be an option under "DPG type" and "SDG" separately and when the user clicks it, either of the two only the options in that category should unlock.

**Comment by prajectory** [comment]
I am reopening this.

**Comment by mlschechter** [comment]
The current "select all" functionality does not appear to work as intended. If I unselect it (unselecting all types and SDGs), I then cannot add back individual items, nor does "select all" restore the original list 

Additionally, if I leave "select all" enabled, and then uncheck each type in turn, then turning them back on does not restore the category to the list.

Using Firefox 115 on Fedora.
