### ISSUE TITLE
UI integrity upon unclicking SDG 

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/publicgoods-website#24]
I have taken a screen recording to highlight what's happening. The scroll is getting affected when none of the SDGs are selected. When the un-clicking goes below one screen scroll, it starts to affect the design and interface. 

https://drive.google.com/file/d/1f3lkl7LQ-Y781pGDRudwuy9BMUhVUiFL/view?usp=sharing

**Comment by PelinSmines** [comment]
This issue is fixed. It can be closed.
