### ISSUE TITLE
Making Example Submissions visible

### ISSUE THREAD

**Issue by JaniceDean** [DPGAlliance/publicgoods-website#3]
I have found that providing example submissions such as [this](https://digitalpublicgoods.net/registry/apache-fineract.html) is very helpful (esp for projects that want to submit). But it is also really hard to find on the website and navigate. I realized scrolling through that I can click on the Green DPG icon for these examples, but it took a few tries from clicking on the yellow ones, fumbling through the menus. 

It would be great to refer to such examples in the submission guide at least. And also refer to these on the "Registry" page and/or the "Digital Public Goods Standard" page on the website.

**Comment by lacabra** [comment]
Thank you @JaniceDean  for your suggestion. Cross-linking it with this other related issue DPGAlliance/technical-roadmap#27

1. The [submission guide](http://digitalpublicgoods.net/submission-guide) is not under version control, so I suggest reaching out to @lucyeoh for changes on that document
2. For references on the [Registry](https://digitalpublicgoods.net/registry/) and the [Standard](https://digitalpublicgoods.net/standard/), we would appreciate specific suggestion on the language. Is there specific text you'd like to suggest?

Thanks again 🙏

**Comment by JaniceDean** [comment]
Sure. For the Registry, we actually are missing text/cues that even point to the fact that some projects are labeled DPG. Perhaps after the sentence "This registry houses digital public goods that have either been nominated directly or have been pulled together from partnership databases.", we can add: "Digital Public Goods that have fully met the current standard, are labeled with <insert orange icon here> and <insert green icon here>. To see the full submission of a Digital Public Good that has met the standards, you can click on the icon <insert green icon> next to the digital public good. 

For the Standard page, we can add right before the sentence "More information on applying and contributing to the standard is below.": To see the full submission of a Digital Public Good that has met the standards, you can click on the icon <insert green icon> next to the digital public good in the Registry.

**Comment by SarahWat** [comment]
Hi Janice! Thanks for this and good flag that this needs to be more explicit on both of these pages. I've adjusted the copy slightly to read: 
"Digital Public Goods that adhere to the DPG Standard, are labeled as a digital public good with a DPG symbol beside their name. To see the full submission of a Digital Public Good that has met the standard, click on the DPG icon." 
However, I realize how we describe this is contingent upon or should be informed by the naming conventions work so will continue to develop over the next few weeks. So, I'll add a note to revisit this when that's finalized.

**Comment by prajectory** [comment]
Each DPG information is showcased on the registry when you click their name. This is therefore resolved. Thanks!
