### ISSUE TITLE
“DPGA’s strategic objectives” links to old strategy guide

### ISSUE THREAD

**Issue by rd170905** [DPGAlliance/publicgoods-website#37]
“DPGA’s strategic objectives” on the roadmap page points to the outdated strategy guide https://digitalpublicgoods.net/DPGA_Strategy_2021-2026.pdf#page=13
Instead of the updated report
https://digitalpublicgoods.net/dpga-strategy2023-2028.pdf

**Comment by PelinSmines** [comment]
![Image](https://github.com/user-attachments/assets/327a4cab-0c7d-40f5-b0d8-dd27f4e64dc8)
