### ISSUE TITLE
Broken link in Eligibility Page

### ISSUE THREAD

**Issue by BolajiAyodeji** [DPGAlliance/publicgoods-website#38]
Hi. It's unclear how to make code or content contributions to this repository. The README says "Submit issues or Pull Requests to change any other content of the site to the [publicgoods-wordpress](https://github.com/unicef/publicgoods-wordpress) repo." but the linked repo is archived. I just want to point out that the link in the `See the full license list here for reference.` statement on the [eligibility page](https://digitalpublicgoods.net/eligibility/) (question two) is broken. I presume that should now point to [the wiki](https://github.com/DPGAlliance/dpg-resources/wiki/2.-Open-Licensing) instead. Do let me know if there's a better docs on how to contribute so I can make the change, else I believe someone else can do this. Thank you!

**Comment by PelinSmines** [comment]
@law909 "See the full license list here for reference". statement on the [eligibility page](https://digitalpublicgoods.net/eligibility/) (question two) is broken. Under question 2, there FAQ and the second question has this link for full license list. It points to a page that doesn't exists. Bolaji sent this link as the correct source that should now point to [the wiki](https://github.com/DPGAlliance/dpg-resources/wiki/2.-Open-Licensing#all-licenses) instead.

**Comment by BolajiAyodeji** [comment]
Thank you @PelinSmines. I should add that the last section (see below) needs to be updated to the same link too (the current one is outdated).

```
For additional resources about open license, please review the link below :
https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/licenses.md
```

All backlinks to the `publicgoods-candidates` repository will now point to the [DPG Wiki](https://github.com/DPGAlliance/dpg-resources/wiki) for the up-to-date help resources.

**Comment by PelinSmines** [comment]
> Thank you [@PelinSmines](https://github.com/PelinSmines). I should add that the last section (see below) needs to be updated to the same link too (the current one is outdated).
> 
> ```
> For additional resources about open license, please review the link below :
> https://github.com/DPGAlliance/publicgoods-candidates/blob/main/help-center/licenses.md
> ```
> 
> All backlinks to the `publicgoods-candidates` repository will now point to the [DPG Wiki](https://github.com/DPGAlliance/dpg-resources/wiki) for the up-to-date help resources.

@law909 could you please consider this also and update accordingly?
