### ISSUE TITLE
Mobile version of the new design

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-website#47]

**Comment by gazdagergo** [comment]
Related FIGMA links:
- https://www.figma.com/proto/T54K9z42eUB0XNhqjYi7YO/Fellesdokument?page-id=104%3A173&node-id=1669-11592&viewport=-10024%2C-1438%2C0.36&t=2PY9JWIwL4L3diPo-8&scaling=scale-down-width&content-scaling=fixed&hide-ui=1
- https://www.figma.com/files/team/1403742107009509794/all-projects?fuid=1314549572154663312
